package gotopo

import (
	"fmt"
	"net/http"
	"net/url"
	"strings"
	"time"
)

// Credentials are the values generated by CalTopo's offline activation flow.
type Credentials struct {
	ID                string
	Key               string
	AccountID         string
	InternetAccountID string
}

// PointValidation controls longitude/latitude validation before mutations.
type PointValidation int

const (
	ValidateAndFixPoints PointValidation = iota
	ValidatePointsOnly
	DisablePointValidation
)

type config struct {
	baseURL         *url.URL
	httpClient      *http.Client
	credentials     Credentials
	syncInterval    time.Duration
	requestTimeout  time.Duration
	caseSensitive   bool
	pointValidation PointValidation
	clock           func() time.Time
	events          EventHandlers
}

// Option configures a Client.
type Option func(*config) error

func defaultConfig() config {
	u, _ := url.Parse("http://localhost:8080")
	return config{
		baseURL: u, httpClient: http.DefaultClient,
		syncInterval: 10 * time.Second, requestTimeout: 10 * time.Second,
		pointValidation: ValidateAndFixPoints, clock: time.Now,
	}
}

// WithEndpoint sets a CalTopo hostname, host:port, or absolute base URL.
func WithEndpoint(endpoint string) Option {
	return func(c *config) error {
		if !strings.Contains(endpoint, "://") {
			scheme := "http"
			switch strings.ToLower(endpoint) {
			case "caltopo.com", "sartopo.com", "testing.caltopo.com":
				scheme = "https"
			}
			endpoint = scheme + "://" + endpoint
		}
		u, err := url.Parse(endpoint)
		if err != nil || u.Host == "" {
			return fmt.Errorf("gotopo: invalid endpoint %q", endpoint)
		}
		u.Path = strings.TrimRight(u.Path, "/")
		c.baseURL = u
		return nil
	}
}

func WithHTTPClient(client *http.Client) Option {
	return func(c *config) error {
		if client == nil {
			return fmt.Errorf("gotopo: nil HTTP client")
		}
		c.httpClient = client
		return nil
	}
}

func WithCredentials(credentials Credentials) Option {
	return func(c *config) error {
		c.credentials = credentials
		return nil
	}
}

func WithSyncInterval(interval time.Duration) Option {
	return func(c *config) error {
		if interval <= 0 {
			return fmt.Errorf("gotopo: sync interval must be positive")
		}
		c.syncInterval = interval
		return nil
	}
}

func WithRequestTimeout(timeout time.Duration) Option {
	return func(c *config) error {
		if timeout <= 0 {
			return fmt.Errorf("gotopo: request timeout must be positive")
		}
		c.requestTimeout = timeout
		return nil
	}
}

func WithCaseSensitiveComparisons(enabled bool) Option {
	return func(c *config) error {
		c.caseSensitive = enabled
		return nil
	}
}

func WithPointValidation(mode PointValidation) Option {
	return func(c *config) error {
		if mode < ValidateAndFixPoints || mode > DisablePointValidation {
			return fmt.Errorf("gotopo: invalid point validation mode")
		}
		c.pointValidation = mode
		return nil
	}
}

func WithEventHandlers(handlers EventHandlers) Option {
	return func(c *config) error {
		c.events = handlers
		return nil
	}
}
